version: '3'
services:
  frontend:
    build:
      context: ../rebounder-chain-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8099:8099"
