version: '3'
services:
  web:
    build:
      context: ../rebounder-chain-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
#  :
#    build:
#      context: .
#      dockerfile: Dockerfile
#      ports:
#        - "8099:8099"